name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating your First Issue. Please connect with [Shoaib](https://www.linkedin.com/in/shoaibrayeen) in case of any issue."
        pr-message: "Thank you for creating your Pull Request. Please connect [Shoaib](https://www.linkedin.com/in/shoaibrayeen) in case of any issue."
